### ISSUE TITLE
(IR) get new  robots running in stage (waiting to confirm  update_catalog robot)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_robots#15]
Once we have 
- [x] a workflow object (#4)
- [x] robot code base ready to go (#9)
- [x] workflow object matches robot code base
- [x] shared_configs for stage/test (#1)
- [x] cap deploy (see #22)

We need to turn off old sdr-preservation-core robots in stage (permanently)

We need to get this new robot code running properly in stage:
- hooked up to redis and showing up in redis,
- showing in argo workflows, 
- fired off automagically at the appropriate time

probably will spawn a ticket:
- write documentation (at robot-master wiki??) on steps needed to create/set up / deploy new robots and have them running.  Also on how to turn off robots, permanently

**Comment by ndushay** [comment]
Will close this ticket after ingest-cleanup is working

**Comment by ndushay** [comment]
made a separate ticket for update-catalog checking in situ.
