### ISSUE TITLE
when available, upgrade preservation-client

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_robots#187]
once https://github.com/sul-dlss/preservation-client/pull/29 is merged and a new version has been cut:
- [ ] update the preservation-client gem (PR #188)
- [ ] add an example token setting in settings.yml (PR #188)
- [ ] update the [`Preservation::Client.configure` call](https://github.com/sul-dlss/preservation_robots/blob/f6a1f768207c47d93544d5b76644a060505ef1e2/config/boot.rb#L39) to use the new setting  (PR #188)
- [x] mint real tokens on stage and prod pres cat servers, and add those token values as corresponding overrides in the stage and prod shared configs settings (PRs sul-dlss/shared_configs/pull/1177, sul-dlss/shared_configs/pull/1178, sul-dlss/shared_configs/pull/1169, sul-dlss/shared_configs/pull/1170)

**Comment by jmartin-sul** [comment]
see also https://github.com/sul-dlss/preservation_catalog/pull/1306 and https://github.com/sul-dlss/preservation_catalog/issues/1298
