### ISSUE TITLE
move the removal/unlinking of the deposit directory content to the top of the `update-catalog` step

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_robots#310]
quick-ish intro: based on a suggestion from @julianmorley and some discussion with @andrewjbtw and @jmartin-sul, we're going to try moving the `remove_deposit_bag` call from `CompleteIngest#complete_ingest` to the beginning of `UpdateCatalog#update_catalog` (we'd also want to move the private `remove_deposit_bag` method from the `CompleteIngest` class to `UpdateCatalog`, since it's a private helper method that's only used in the one place).  For an abundance of context, see https://github.com/sul-dlss/preservation_robots/issues/307.

This is a pretty straight-forward code change, and none of us (@julianmorley, @andrewjbtw, and @jmartin-sul) can imagine any problems the change would introduce.  Additionally, we hope that it will alleviate [pres robots and pres cat issues with reading from Ceph backed storage](https://github.com/sul-dlss/preservation_catalog/issues/1633) (these problems are still occurring, albeit at a greatly reduced rate since a Ceph upgrade a few weeks ago, though the remaining work has been captured in more discreet tickets such as this and #307).

#### TODO, in order
- [x] Move the `remove_deposit_bag` definition from the `CompleteIngest` class to `UpdateCatalog`, and move the `remove_deposit_bag` call to the top of `UpdateCatalog#update_catalog`, right before the `wait_as_needed` call.  Code snippets linked below.
- [x] Work with @andrewjbtw to come up with a plan for testing the change once it's been deployed to stage.  My first instinct is that the following would be sufficient:
  - [x] Do the manual testing described in Andrew's [comment on issue 307](https://github.com/sul-dlss/preservation_robots/issues/307#issuecomment-827249831).  Confirm that the content has been preserved locally among the Moab storage roots, and replicated to all three cloud endpionts.  @jmartin-sul is happy to pair to point to Wiki and README entries that can help with this.  Can also drop links and explanation if synchronous pairing would be a pain.
  - [x] Run the infra integration test suite.  Confirm that all tests pass, and that the content created in at least `create_preassembly_image_spec.rb` (if not also `sdr_deposit_spec.rb` and `deposit_via_hydrus_spec.rb`) has been preserved and replicated as described in the other manual test step.
  - [x] Before merging, let the pres robots branch run in stage for a few days.  Watch the [robots Resque console](https://robot-console-stage.stanford.edu/overview) (esp `preservationIngestWF_*` queues) and the [pres cat Resque console](https://preservation-catalog-stage-01.stanford.edu/resque/overview) for new errors.
- [x] If all's well on the testing front, merge to `main`, and deploy to prod.
- [x] Keep a close eye on the prod Resque consoles for a few days, as was done w/ stage testing.

The last two bullet points should be handled by one first responder, preferably in the morning and earlier in the week, to allow for adequate babysitting.  The other steps can be handled piecemeal by different first responders, as long as they happen in sequence and the changes don't get merged to `main` early.  If someone picks this up and does not close the ticket, please hand it off to the subsequent first responder.

Relevant code:
https://github.com/sul-dlss/preservation_robots/blob/1c1032af89f6fabe84831a419b66fac5c24b79ef/lib/robots/sdr_repo/preservation_ingest/update_catalog.rb#L35-L43
https://github.com/sul-dlss/preservation_robots/blob/1c1032af89f6fabe84831a419b66fac5c24b79ef/lib/robots/sdr_repo/preservation_ingest/complete_ingest.rb#L23-L28
https://github.com/sul-dlss/preservation_robots/blob/1c1032af89f6fabe84831a419b66fac5c24b79ef/lib/robots/sdr_repo/preservation_ingest/complete_ingest.rb#L30-L46

**Comment by jmartin-sul** [comment]
The change seems to be working in production without issue -- we are still experiencing some Ceph read errors for updated content, but we've at least experienced no regression in that we've not created any corrupt Moab versions due to this change.

Because of an unrelated puppet change that caused a blip in Ceph-backed storage root availability on Wed of this week, right after the change for this issue was deployed (deployed 3:10 pm/blip ~3:45-5 pm), I ran pres cat's checksum validation on all Moabs in preservation modified between 3 pm 2021-06-02 and about 11:45 pm 2021-06-03.  A few (14) were not available for read from Ceph, and so couldn't complete checksum validation, but the rest of the approximately 6000 Moabs that were audited passed checksum validation.

Will continue to watch for a couple days, but closing this issue, as things seem fine so far. (Will also contact ops about the 14 druids that had unavailable files)
